CREATE DATABASE IF NOT EXISTS TreasuryDB;
USE TreasuryDB;

CREATE TABLE IF NOT EXISTS ExchangeRates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    currency_pair VARCHAR(10),
    rate DECIMAL(10,4),
    source VARCHAR(50),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
