CREATE DATABASE IF NOT EXISTS TreasuryDB;
USE TreasuryDB;

CREATE TABLE IF NOT EXISTS ExchangeRates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    currency_pair VARCHAR(10) NOT NULL,
    rate DECIMAL(10,4) NOT NULL,
    source VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
